[project]
name = "agentic-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai[tools]>=1.5.0",
    "fastapi>=0.121.1",
    "gradio>=5.49.1",
    "jupyter>=1.1.1",
    "mailjet-rest>=1.5.1",
    "openai>=2.7.1",
    "openai-agents>=0.4.2",
    "pypdf>=6.2.0",
    "python-dotenv>=1.2.1",
]
