coding_task:
  description: >
    write python code to achieve the this: {assignment}
  expected_output: >
    A text file containing the Python code that fulfills the assignment requirements along with the output of the code.
  agent: developer
  output_file: output/developer_code.txt 
  